# Generated by Django 3.0.8 on 2020-07-24 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='image',
            new_name='cover_image',
        ),
    ]
