# Generated by Django 3.0.8 on 2020-07-24 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20200724_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cover_image',
            field=models.ImageField(default='articles/static/articles/image/cardimage.jpg', upload_to='media/'),
        ),
    ]
