# Generated by Django 3.0.8 on 2020-07-27 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20200724_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cover_image',
            field=models.ImageField(default='media/media/cardimage.jpg', upload_to='media/'),
        ),
    ]
